### ISSUE TITLE
Use Generic Type instead of Object in TelemetryDataProvider.

### ISSUE THREAD

**Issue by arunj-kp** [juechemparathy/telemetry#4]
May be it is better to add Generic type as this:
public abstract class TelemetryDataProvider<T> {
    private final String fieldName;

    public TelemetryDataProvider(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getFieldName() {
        return fieldName;
    }

    public abstract T prepare();
}

**Comment by juechemparathy** [comment]
@arunj-kp
